version: '3'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - '.:/app'
      - assets:/app/assets
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
  frontend:
    restart: always
    image: node:alpine
    command: "yarn run --cwd=/app webpack"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - assets:/app/assets

volumes:
  assets:
  node_modules: